# 01-14-25 Lab 2
## Matrix Multiplication

In [3]:
import numpy as np

A = np.random.rand(3,4)
B = np.random.rand(4,5)

In [22]:
lhs = (A @ B).T
lhs

array([[0.73631605, 1.04572926, 0.35806599],
       [1.03739468, 0.92947108, 0.31898652],
       [1.50383101, 1.44470974, 0.52606721],
       [1.29957375, 1.43905025, 0.49682792],
       [0.71177025, 0.82144439, 0.47741766]])

In [5]:
rhs = B.T @ A.T
rhs

array([[0.73631605, 1.04572926, 0.35806599],
       [1.03739468, 0.92947108, 0.31898652],
       [1.50383101, 1.44470974, 0.52606721],
       [1.29957375, 1.43905025, 0.49682792],
       [0.71177025, 0.82144439, 0.47741766]])

In [23]:
np.ravel(lhs)

array([0.73631605, 1.04572926, 0.35806599, 1.03739468, 0.92947108,
       0.31898652, 1.50383101, 1.44470974, 0.52606721, 1.29957375,
       1.43905025, 0.49682792, 0.71177025, 0.82144439, 0.47741766])

In [24]:
lhs.flatten()

array([0.73631605, 1.04572926, 0.35806599, 1.03739468, 0.92947108,
       0.31898652, 1.50383101, 1.44470974, 0.52606721, 1.29957375,
       1.43905025, 0.49682792, 0.71177025, 0.82144439, 0.47741766])

In [8]:
np.ravel(rhs.T)

array([0.73631605, 1.03739468, 1.50383101, 1.29957375, 0.71177025,
       1.04572926, 0.92947108, 1.44470974, 1.43905025, 0.82144439,
       0.35806599, 0.31898652, 0.52606721, 0.49682792, 0.47741766])